version: '3'
services:

  ghost:
    image: ghost:latest
    ports:
      - 2368:2368
    restart: always
    depends_on:
      - db
    environment:
      url: https://hostbrine.com
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: root
      database__connection__database: ghost
    volumes:
        - ../content:/var/lib/ghost/content
        
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ../mysql:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
